# DOCKERHUB_USERNAME  username
# DOCKERHUB_PASSWORD  secret
# DOCKERHUB_NAMESPACE namespace
# DOCKERHUB_IMAGE     image

stages:
  - build
  - release
  - silly

build:
  stage: build
  only:
    refs:
      - branches
      - tags
    changes:
      - Dockerfile
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker image pull $CI_REGISTRY_IMAGE:alpine || true
    - > 
      docker image build 
      --pull
      --tag $CI_REGISTRY_IMAGE:alpine
      --cache-from $CI_REGISTRY_IMAGE:alpine
      .   
    - docker image push $CI_REGISTRY_IMAGE:alpine
    - docker logout $CI_REGISTRY

release:
  stage: release
  dependencies:
    - build
  only:
    refs:
      - tags
    changes:
      - Dockerfile
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    GIT_STRATEGY: none
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker image pull $CI_REGISTRY_IMAGE:alpine
    - docker image tag $CI_REGISTRY_IMAGE:alpine $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker image push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker logout $CI_REGISTRY
    - docker image tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $DOCKERHUB_NAMESPACE/$DOCKERHUB_IMAGE:$CI_COMMIT_REF_NAME
    - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
    - docker image push $DOCKERHUB_NAMESPACE/$DOCKERHUB_IMAGE:$CI_COMMIT_REF_NAME
    - docker logout

silly:
  stage: silly
  script:
    - echo "You silly."
